# Generated by Django 4.1.3 on 2022-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="addOption",
            field=models.CharField(default="null", max_length=140),
        ),
    ]
